"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";

export default function ApiTestButton() {
  const [loading, setLoading] = useState(false);
  const router = useRouter();

  const testApi = async () => {
    setLoading(true);
    try {
      const response = await fetch("/api/lore", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          title: "Test Lore Entry",
          content: "This is a test lore entry generated by the API test button.",
          author: "Admin Test",
          channelName: "test-channel",
        }),
      });
      
      if (response.ok) {
        alert("API test successful! Reloading page...");
        router.refresh();
      } else {
        const errorData = await response.json();
        alert(`API test failed: ${errorData.error}`);
      }
    } catch (error) {
      console.error(error);
      alert("API test failed due to network error.");
    } finally {
      setLoading(false);
    }
  };

  const testAiApi = async () => {
    setLoading(true);
    try {
      const response = await fetch("/api/ai", {
        method: "POST",
      });
      
      if (response.ok) {
        const data = await response.json();
        alert(`AI says: ${data.message}`);
      } else {
        const errorData = await response.json();
        alert(`AI test failed: ${errorData.error}`);
      }
    } catch (error) {
      console.error(error);
      alert("AI test failed due to network error.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="flex gap-4 mt-6">
      <button
        onClick={testApi}
        disabled={loading}
        className="px-6 py-3 bg-amber-600 hover:bg-amber-500 text-white font-medium rounded-lg shadow-lg hover:shadow-xl transition-all duration-300 disabled:opacity-50"
      >
        {loading ? "Testing..." : "Test Lore API"}
      </button>
      <button
        onClick={testAiApi}
        disabled={loading}
        className="px-6 py-3 bg-indigo-600 hover:bg-indigo-500 text-white font-medium rounded-lg shadow-lg hover:shadow-xl transition-all duration-300 disabled:opacity-50"
      >
        {loading ? "Testing..." : "Test AI API"}
      </button>
    </div>
  );
}
